language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home Directory
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - virusetkill@gmail.com

before_install:
  - chmod +x ./gradlew

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv  freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIAT7HEHL36IWJKYW4N
    secret_access_key: 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

    bucket: freelec-springboot-byhorizon-build #S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait_until_deployed : true


